//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MuhendislikYagmur
{
    using System;
    using System.Collections.Generic;
    
    public partial class iller
    {
        public iller()
        {
            this.Ozellikler = new HashSet<Ozellikler>();
        }
    
        public int ID { get; set; }
        public string iladi { get; set; }
    
        public virtual ICollection<Ozellikler> Ozellikler { get; set; }
    }
}
